# Generated by Django 6.0.3 on 2026-03-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Signature'), ('signed', 'Signed')], default='pending', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/pdf/')),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.clientprofile')),
            ],
        ),
    ]
