# Generated by Django 6.0.3 on 2026-03-20 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('admin-sales', 'Admin & Sales'), ('2d-design', '2D Design')], max_length=20)),
                ('work_preference', models.CharField(choices=[('home', 'Home-Based'), ('office', 'Office-Based')], max_length=10)),
                ('experience', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidates/cv/')),
                ('voice_intro', models.FileField(blank=True, null=True, upload_to='candidates/voice/')),
                ('status', models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('update', 'Update Requested')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
